routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth','admin'], 'namespace' => 'Admin'], function (){
    //clients
    Route::get('clients', 'ClientController@index');
    Route::get('clients/create', 'ClientController@create');
    Route::post('clients/create', 'ClientController@store');
    Route::get('clients/{id}/edit', 'ClientController@edit');
    Route::post('clients/{id}/edit', 'ClientController@update');
    Route::get('clients/{id}/delete', 'ClientController@delete');
    //rates
    Route::get('rates', 'RateController@index');
    Route::get('rates/create', 'RateController@create');
    Route::post('rates/create', 'RateController@store');
    Route::get('rates/{id}/edit', 'RateController@edit');
    Route::post('rates/{id}/edit', 'RateController@update');
    Route::get('rates/{id}/delete', 'RateController@delete');
    //taxes
    Route::get('rates/{id}/taxes', 'TaxController@index');
    Route::get('rates/{id}/taxes/create', 'TaxController@create');
    Route::post('rates/{id}/taxes/create', 'TaxController@store');
    Route::get('taxes/{tax_id}/edit', 'TaxController@edit');
    Route::post('taxes/{tax_id}/edit', 'TaxController@update');
    Route::get('taxes/{tax_id}/delete', 'TaxController@delete');
    //accounts
    Route::get('accounts', 'AccountController@index');
    Route::get('accounts/create', 'AccountController@create');
    Route::post('accounts/create', 'AccountController@store');
    Route::get('accounts/{id}/edit', 'AccountController@edit');
    Route::post('accounts/{id}/edit', 'AccountController@update');
    Route::get('accounts/{id}/delete', 'AccountController@delete');

    //tributes
    Route::get('tributes', 'TributeController@index');
    Route::get('tributes/create', 'TributeController@create');
    Route::post('tributes/create', 'TributeController@store');
    Route::get('tributes/{id}/show', 'TributeController@show');
    Route::get('tributes/{id}/edit', 'TributeController@edit');
    Route::post('tributes/{id}/edit', 'TributeController@update');
    Route::get('tributes/{id}/delete', 'TributeController@delete');

    //batch tributes
    Route::get('entries', 'EntryController@index');
    Route::get('entries/create', 'EntryController@create');
    Route::post('entries/create', 'EntryController@store');

    //payment
    Route::get('payments', 'PaymentController@index');
    Route::get('payments/create', 'PaymentController@create');
    Route::post('payments/create', 'PaymentController@store');
    Route::get('payments/{id}/show', 'PaymentController@show');
    Route::get('payments/{id}/edit', 'PaymentController@edit');
    Route::post('payments/{id}/edit', 'PaymentController@update');
    Route::get('payments/{id}/delete', 'PaymentController@delete');

    // Search
    Route::get('rate/search', 'RateSearchController@index');
});

app/Entry.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Entry extends Model
{
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function details()
    {
        return $this->hasMany(EntryDetail::class);
    }

    public function getCreatedFormatAttribute()
    {
        return $this->created_at->format('d-m-Y');
    }

    public function getTotalAttribute()
    {
        return $this->details()->sum('col_12');
    }
}

app/Http/Controllers/Admin/EntryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Entry;
use App\EntryDetail;
use Exception;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;

class EntryController extends Controller
{
    public function index()
    {
        $entries = Entry::orderBy('created_at')->get();

        return view('admin.entries.index', compact('entries'));
    }

    public function create()
    {
        return view('admin.entries.create');
    }

    public function store(Request $request)
    {
        $rules = [
            'file' => 'required|mimes:csv,txt'
        ];
        $messages = [
            'file.mimes' => 'Los datos se deben cargar a través de un archivo CSV.'
        ];
        $this->validate($request, $rules, $messages);

        try {
            DB::beginTransaction();
            $file = $request->file('file');
            $lines = file($file);
            $utf8_lines = array_map('utf8_encode', $lines);
            $array = array_map(function($v){return str_getcsv($v, "\t");}, $utf8_lines);

            $entry = new Entry();
            $entry->name = $request->name;
            $entry->user_id = auth()->id();
            $entry->save();

            for ($i=0; $i<sizeof($array); ++$i) {
                $col1 = $array[$i][0];
                $col2 = $array[$i][1];
                $col3 = $array[$i][2];
                $col4 = $array[$i][3];
                $col5 = $array[$i][4];
                $col6 = $array[$i][5];
                $col7 = $array[$i][6];
                $col8 = $array[$i][7];
                $col9 = $array[$i][8];
                $col10 = $array[$i][9];
                $col11 = $array[$i][10];
                $col12 = $array[$i][11];
                $col13 = $array[$i][12];

                $entryDetail = new EntryDetail();
                $entryDetail->col_1 = $col1;
                $entryDetail->col_2 = $col2;
                $entryDetail->col_3 = $col3;
                $entryDetail->col_4 = $col4;
                $entryDetail->col_5 = $col5;
                $entryDetail->col_6 = $col6;
                $entryDetail->col_7 = $col7;
                $entryDetail->col_8 = $col8;
                $entryDetail->col_9 = $col9;
                $entryDetail->col_10 = $col10;
                $entryDetail->col_11 = $col11;
                $entryDetail->col_12 = $col12;
                $entryDetail->col_13 = $col13;
                $entryDetail->entry_id = $entry->id;
                $entryDetail->save();
            }
            DB::commit();
            return redirect('entries')->with('notification', 'Se registró correctamente.');

        } catch (Exception $e) {

            DB::rollback();
            return redirect('/entries/create')->with('notification', $e->getMessage());
//            return redirect('/entries/create')->with('notification', 'El archivo cargado no tiene un formato correcto.');
        }
    }
}

resources/views/admin/entries/create.blade.php
@extends('layouts.app')

@section('content')
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ url('entries') }}">Gestión de ingreso por lotes</a></li>
            <li class="breadcrumb-item active">Nuevo ingreso</li>
        </ol>
    </nav>
    <div class="card">
        <div class="card-header text-white bg-dark">Nuevo cobro</div>

        <div class="card-body">
            @if (session('notification'))
                <div class="alert alert-success" role="alert">
                    {{ session('notification') }}
                </div>
            @endif
            <form method="post" enctype="multipart/form-data">
                @csrf
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label for="name" class="col-form-label">Tasa</label>
                            <input type="text" class="form-control" id="name" name="name" value="{{ old('name') }}" required>
                        </div>
                        @error('name')
                        <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span>
                        @enderror
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label for="file" class="col-form-label">Archivo .csv</label>
                            <div class="custom-file">
                                <label class="custom-file-label" for="file">Seleccionar Archivo</label>
                                <input type="file" class="custom-file-input" id="file" name="file"  accept=".csv" required>
                            </div>
                            @error('file')
                            <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span>
                            @enderror
                        </div>
                    </div>
                </div>
                <div class="form-group row mt-3">
                    <div class="col-sm-10">
                        <button type="submit" class="btn btn-primary">Registrar</button>
                        <a href="{{ asset('entries') }}" class="btn btn-secondary">Cancelar</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection
@section('scripts')

@endsection

resources/views/admin/entries/index.blade.php
@extends('layouts.app')

@section('content')
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item active">Gestión de ingreso por lotes</li>
        </ol>
    </nav>
    <div class="card">
        <div class="card-header text-white bg-dark">Gestión de ingreso por lotes</div>

        <div class="card-body">
            @include('includes.alerts')
            <div class="row">
                <div class="col-sm-8">
                    {{--<form>--}}
                        {{--<div class="form-row align-items-center">--}}
                            {{--<div class="col-auto">--}}
                                {{--<input type="text" class="form-control mb-2" id="inlineFormInput" placeholder="Buscar">--}}
                            {{--</div>--}}
                            {{--<div class="col-auto">--}}
                                {{--<button type="submit" class="btn btn-dark mb-2">Buscar</button>--}}
                            {{--</div>--}}
                        {{--</div>--}}
                    {{--</form>--}}
                </div>
                <div class="col-sm-4">
                    <a href="{{ asset('entries/create') }}" class="btn btn-dark float-right">Nuevo ingreso</a>
                </div>
            </div>
                <table class="table table-sm my-3">
                    <thead class="thead-light">
                        <tr>
                            <th>#</th>
                            <th>Tasa</th>
                            <th>Total</th>
                            <th>Registros</th>
                            <th>F emisión</th>
                            <th>Usuario</th>
                            <th>Opciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($entries as $entry)
                            <tr>
                                <td>{{ $entry->id }}</td>
                                <td>{{ $entry->name }}</td>
                                <td>{{ $entry->total }}</td>
                                <td>{{ $entry->details->count() }}</td>
                                <td>{{ $entry->created_format }}</td>
                                <td>{{ $entry->user->name }}</td>
                                <td>
                                    <a href="#" class="btn btn-sm btn-primary">Ingresar</a>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
        </div>
    </div>
@endsection